-- =====================================================================
--  Seed: 52 recetas del Taller de Cocteleria
--  GENERADO por sql/fuente/build_seed.php - no editar a mano.
--  Regenerar:  php sql/fuente/build_seed.php
--  Requiere haber corrido antes sql/schema.sql
-- =====================================================================

SET NAMES utf8mb4;
START TRANSACTION;

DELETE FROM recipe_tags;
DELETE FROM recipe_ingredients;
DELETE FROM recipe_topics;
DELETE FROM recipes;
DELETE FROM tags;

-- ---------- tags ----------
INSERT INTO tags (id, name, slug) VALUES
  (1, 'Albahaca', 'albahaca'),
  (2, 'Amargo Obrero', 'amargo-obrero'),
  (3, 'Angostura', 'angostura'),
  (4, 'Aperol', 'aperol'),
  (5, 'Apricot Brandy', 'apricot-brandy'),
  (6, 'Brandy', 'brandy'),
  (7, 'Cachaca', 'cachaca'),
  (8, 'Cafe', 'cafe'),
  (9, 'Campari', 'campari'),
  (10, 'Cassis', 'cassis'),
  (11, 'Chartreuse', 'chartreuse'),
  (12, 'Cherry Brandy', 'cherry-brandy'),
  (13, 'Citrico', 'citrico'),
  (14, 'Con Huevo', 'con-huevo'),
  (15, 'Cynar', 'cynar'),
  (16, 'Espumante', 'espumante'),
  (17, 'Fernet', 'fernet'),
  (18, 'Frutilla', 'frutilla'),
  (19, 'Gin', 'gin'),
  (20, 'Hesperidina', 'hesperidina'),
  (21, 'Hierro Quina', 'hierro-quina'),
  (22, 'Jengibre', 'jengibre'),
  (23, 'Licor Cafe', 'licor-cafe'),
  (24, 'Licor Crema', 'licor-crema'),
  (25, 'Malibu', 'malibu'),
  (26, 'Menta', 'menta'),
  (27, 'Mezcal', 'mezcal'),
  (28, 'Pimms', 'pimms'),
  (29, 'Pineral', 'pineral'),
  (30, 'Pisco', 'pisco'),
  (31, 'Pomelo', 'pomelo'),
  (32, 'Ron', 'ron'),
  (33, 'Sin Alcohol', 'sin-alcohol'),
  (34, 'Strega', 'strega'),
  (35, 'Tequila', 'tequila'),
  (36, 'Triple Sec', 'triple-sec'),
  (37, 'Vermut', 'vermut'),
  (38, 'Vodka', 'vodka'),
  (39, 'Whisky', 'whisky');

-- ---------- recipes ----------
INSERT INTO recipes (id, name, slug, glassware, ice, method, method_other, method_detail, volume, moment, family_id, garnish, description) VALUES
  (1, 'Mojito', 'mojito', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, NULL, 'Hoja de menta', NULL),
  (2, 'Rojito', 'rojito', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, NULL, 'Hoja de menta', NULL),
  (3, 'Cynar Julep', 'cynar-julep', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, (SELECT id FROM families WHERE slug = 'julep'), 'Hoja de menta', NULL),
  (4, 'Pineral Julep', 'pineral-julep', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, (SELECT id FROM families WHERE slug = 'julep'), 'Hoja de menta', NULL),
  (5, 'Hesperidina Julep', 'hesperidina-julep', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, (SELECT id FROM families WHERE slug = 'julep'), 'Hoja de menta', NULL),
  (6, 'Cassis Julep', 'cassis-julep', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, (SELECT id FROM families WHERE slug = 'julep'), 'Hoja de menta', NULL),
  (7, 'Julep del Giardino', 'julep-del-giardino', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, (SELECT id FROM families WHERE slug = 'julep'), 'Hoja de menta', NULL),
  (8, 'Fierro en la espalda', 'fierro-en-la-espalda', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, NULL, 'Hoja de menta', NULL),
  (9, 'Mint Julep', 'mint-julep', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, (SELECT id FROM families WHERE slug = 'julep'), 'Hoja de menta', NULL),
  (10, 'Pimm''s Julep', 'pimm-s-julep', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, (SELECT id FROM families WHERE slug = 'julep'), 'Hoja de menta', NULL),
  (11, 'Jardín Violeta', 'jardin-violeta', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, NULL, 'Hoja de menta', NULL),
  (12, 'Mojito Malibú', 'mojito-malibu', 'Vaso trago largo', 'Molido', 'integrado', NULL, 'Integrado con cucharilla', 'long', NULL, NULL, 'Hoja de menta', NULL),
  (13, 'Rob Roy', 'rob-roy', 'Copa Cóctel', NULL, 'refrescado_directo', NULL, 'Refrescado / Batida Cubana', 'short', NULL, NULL, 'Cereza / Piel de Naranja', NULL),
  (14, 'Dry Martini', 'dry-martini', 'Copa Cóctel', NULL, 'refrescado_directo', NULL, 'Refrescado / Batida Cubana', 'short', NULL, NULL, 'Aceitunas / Piel de Limón (clarito)', NULL),
  (15, 'Claridge Cocktail', 'claridge-cocktail', 'Copa Cóctel', NULL, 'refrescado_directo', NULL, 'Refrescado / Batida Cubana', 'short', NULL, NULL, 'Piel de Naranja', NULL),
  (16, 'Hanky Panky', 'hanky-panky', 'Vaso corto estilo Old Fashioned', 'Cubo grande', 'refrescado_directo', NULL, 'Refrescado / Batida Cubana', 'short', NULL, NULL, 'Cereza / Piel de Naranja', NULL),
  (17, 'Mi-To', 'mi-to', 'Vaso Old Fashioned', 'En cubos', 'refrescado_directo', NULL, 'Directo / Refrescado', 'short', NULL, (SELECT id FROM families WHERE slug = 'duo'), 'Piel de Naranja', NULL),
  (18, 'Negroni', 'negroni', 'Vaso Old Fashioned', 'En cubos', 'refrescado_directo', NULL, 'Directo / Refrescado', 'short', NULL, (SELECT id FROM families WHERE slug = 'trio'), '½ rodaja de Naranja', NULL),
  (19, 'Black Russian', 'black-russian', 'Vaso corto estilo Old Fashioned', 'Cubo grande', 'refrescado_directo', NULL, 'Directo / Refrescado (opcional agregar dilución)', 'short', NULL, (SELECT id FROM families WHERE slug = 'duo'), NULL, NULL),
  (20, 'Aperol Spritz', 'aperol-spritz', 'Copón de vino tinto / vaso highball', 'Rolito/cubo', 'refrescado_directo', NULL, 'Directo', 'long', NULL, NULL, '2 medias rodajas de naranja', NULL),
  (21, 'Americano', 'americano', 'Vaso trago largo', 'Rolito/cubo', 'refrescado_directo', NULL, 'Directo', 'long', NULL, NULL, 'Twist o media rodaja de naranja', NULL),
  (22, 'Negroni Sbagliato', 'negroni-sbagliato', 'Vaso Old Fashioned', 'En cubos', 'refrescado_directo', NULL, 'Directo', 'short', NULL, (SELECT id FROM families WHERE slug = 'trio'), '½ rodaja de naranja', NULL),
  (23, 'Coloradito', 'coloradito', 'Copa Cóctel', NULL, 'refrescado_directo', NULL, 'Refrescado / Batida Cubana', 'short', NULL, NULL, 'Piel de Limón', NULL),
  (24, 'Ferroviario', 'ferroviario', 'Vaso trago largo', 'Rolito/cubo', 'refrescado_directo', NULL, 'Directo', 'long', NULL, NULL, 'Twist o media rodaja de naranja', NULL),
  (25, 'Old Fashioned', 'old-fashioned', 'Vaso corto estilo Old Fashioned', 'Cubo grande', 'refrescado_directo', NULL, 'Directo', 'short', NULL, (SELECT id FROM families WHERE slug = 'on-the-rocks'), 'Piel/media rodaja de naranja + 1 cereza', NULL),
  (26, 'Aviation', 'aviation', 'Copa Cocktail / Old Fashioned (con hielo en cubos)', NULL, 'batido', NULL, 'Batido y Doble Colado', 'short', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Cereza / Piel de Limón', NULL),
  (27, 'Pisco Sour', 'pisco-sour', 'Old Fashioned (con hielo en cubos)', NULL, 'batido', NULL, 'Batido en seco, batido y colado simple', 'short', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Piel de Limón + lágrima de Bitter Angostura', NULL),
  (28, 'Daiquiri', 'daiquiri', 'Copa Cocktail', NULL, 'batido', NULL, 'Batido y Doble Colado', 'short', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Piel de Limón', NULL),
  (29, 'Daiquiri "Hemingway"', 'daiquiri-hemingway', 'Copa Cocktail', NULL, 'batido', NULL, 'Batido y Doble Colado', 'short', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Piel de Limón/Pomelo', NULL),
  (30, 'Last Word', 'last-word', 'Copa Cocktail', NULL, 'batido', NULL, 'Batido y Doble Colado', 'short', NULL, NULL, 'Piel de Limón o una cereza', NULL),
  (31, 'Playmate Martini', 'playmate-martini', 'Copa Cocktail', NULL, 'batido', NULL, 'Batido en seco, batido y doble colado', 'short', NULL, NULL, 'Piel de Naranja o media rodaja', NULL),
  (32, 'Tom Collins', 'tom-collins', 'Vaso trago largo', 'Rolito/cubo', 'batido', NULL, 'Batido y doble colado', 'long', NULL, (SELECT id FROM families WHERE slug = 'collins'), 'Twist o media rodaja de limón', NULL),
  (33, 'French 75', 'french-75', 'Vaso trago largo', 'Rolito/cubo', 'batido', NULL, 'Batido y doble colado', 'long', NULL, (SELECT id FROM families WHERE slug = 'fizz'), 'Twist o media rodaja de limón', NULL),
  (34, 'Citro Caipiroska', 'citro-caipiroska', 'Vaso corto', 'Rolito/cubo', 'batido', NULL, 'Batido y doble colado', 'short', NULL, NULL, 'Twist o media rodaja de naranja', NULL),
  (35, 'Bee''s Knees', 'bee-s-knees', 'Copa Cóctel', 'En cubos', 'batido', NULL, 'Batido y doble colado', 'short', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Piel de limón', NULL),
  (36, 'Penicillin', 'penicillin', 'Vaso Old Fashioned', 'Rolito/cubo', 'batido', NULL, 'Batido y doble colado', 'short', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Rodaja de jengibre o piel de limón', NULL),
  (37, 'Naked & Famous', 'naked-famous', 'Copa Cocktail', NULL, 'batido', NULL, 'Batido y Doble Colado', 'short', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Piel de limón o media rodaja', NULL),
  (38, 'Lucha de clases', 'lucha-de-clases', 'Vaso trago largo', 'Rolito/cubo', 'batido', NULL, 'Batido y doble colado', 'long', NULL, NULL, 'Twist o un gajo de mandarina', NULL),
  (39, 'Gin Basil Smash', 'gin-basil-smash', 'Old Fashioned con hielo', 'Rolito/cubo', 'machacado', NULL, 'Machacado, batido y doble colado', 'short', NULL, (SELECT id FROM families WHERE slug = 'smash'), 'Hojas de albahaca', NULL),
  (40, 'Ernest Happel', 'ernest-happel', 'Copa Cóctel', NULL, 'batido', NULL, 'Batido y doble colado', 'short', NULL, NULL, 'Piel de limón o media rodaja', NULL),
  (41, 'Ron Smash', 'ron-smash', 'Old Fashioned con hielo', 'Rolito/cubo', 'machacado', NULL, 'Machacado, batido y doble colado', 'short', NULL, (SELECT id FROM families WHERE slug = 'smash'), 'Hojas de menta', NULL),
  (42, 'The Broady', 'the-broady', 'Copa Cóctel', NULL, 'batido', NULL, 'Batido y doble colado', 'short', NULL, NULL, 'Piel de naranja o media rodaja', NULL),
  (43, 'Cherry Brandy Sour', 'cherry-brandy-sour', 'Old Fashioned con hielo', NULL, 'batido', NULL, 'Batido seco, batido y colado simple', 'short', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Piel de limón o media rodaja', NULL),
  (44, 'Laburante', 'laburante', 'Vaso trago largo', 'Rolito/cubo', 'batido', NULL, 'Batido y doble colado', 'long', NULL, NULL, 'Twist o media rodaja de limón', NULL),
  (45, 'Margarita', 'margarita', 'Copa Cocktail / Old Fashioned (con hielo en cubos)', NULL, 'batido', NULL, 'Batido y Doble Colado', 'short', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Labiado de sal/azúcar + media rodaja de limón', NULL),
  (46, 'Caipirinha', 'caipirinha', 'Old Fashioned', 'Molido', 'machacado', NULL, 'Machacado y batido', 'short', NULL, NULL, 'Rodaja de lima', 'Nota: Caipiroska y Caipirísima reemplazan la cachaça por vodka o ron respectivamente.'),
  (47, 'Daiquiri Frozen de Frutilla', 'daiquiri-frozen-de-frutilla', 'Copa Hurricane', 'Molido', 'frozen', NULL, 'Frozen en licuadora', 'long', NULL, (SELECT id FROM families WHERE slug = 'sour'), 'Frutilla', NULL),
  (48, 'Straw Baileys Frozen', 'straw-baileys-frozen', 'Copa Hurricane', 'Molido', 'frozen', NULL, 'Frozen en licuadora', 'long', NULL, NULL, 'Frutilla + salsa de chocolate', NULL),
  (49, 'Lemmon Champ', 'lemmon-champ', 'Copa Hurricane', 'Molido', 'frozen', NULL, 'Frozen en licuadora', 'long', NULL, NULL, 'Media rodaja de limón', NULL),
  (50, 'The Coffee Latte Cocktail', 'the-coffee-latte-cocktail', 'Vaso Old Fashioned', 'En cubos', 'batido', NULL, 'Batido y colado', 'short', NULL, NULL, 'Canela en rama / chocolate rallado / cacao en polvo', NULL),
  (51, 'Limonada', 'limonada', 'Vaso trago largo', 'Rolito/cubo', 'refrescado_directo', NULL, 'Directo', 'long', NULL, (SELECT id FROM families WHERE slug = 'mocktail'), 'Twist o media rodaja de limón', NULL),
  (52, 'Jarra de Limonada', 'jarra-de-limonada', 'Jarra de 1,25 lts', 'Rolito/cubo', 'refrescado_directo', NULL, 'Directo', 'long', NULL, (SELECT id FROM families WHERE slug = 'mocktail'), NULL, NULL);

-- ---------- recipe_ingredients ----------
INSERT INTO recipe_ingredients (recipe_id, raw_text, amount, unit, position) VALUES
  (1, '60 ml. de Ron Blanco', 60, 'ml', 1),
  (1, '30 ml. de Jugo de Limón', 30, 'ml', 2),
  (1, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (1, '10/12 hojas de menta', 10, 'hoja', 4),
  (1, 'Completar con soda', NULL, NULL, 5),
  (2, '60 ml. de Campari', 60, 'ml', 1),
  (2, '30 ml. de Jugo de Limón', 30, 'ml', 2),
  (2, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (2, '10/12 hojas de menta', 10, 'hoja', 4),
  (2, 'Completar con agua tónica', NULL, NULL, 5),
  (3, '60 ml. de Cynar', 60, 'ml', 1),
  (3, '30 ml. de Jugo de Pomelo Rosado', 30, 'ml', 2),
  (3, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (3, '10/12 hojas de menta', 10, 'hoja', 4),
  (3, 'Completar con soda', NULL, NULL, 5),
  (4, '60 ml. de Pineral', 60, 'ml', 1),
  (4, '30 ml. de Jugo de Pomelo Rosado', 30, 'ml', 2),
  (4, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (4, '10/12 hojas de menta', 10, 'hoja', 4),
  (4, 'Completar con agua tónica', NULL, NULL, 5),
  (5, '60 ml. de Hesperidina', 60, 'ml', 1),
  (5, '30 ml. de Jugo de Naranja', 30, 'ml', 2),
  (5, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (5, '10/12 hojas de menta', 10, 'hoja', 4),
  (5, 'Completar con soda', NULL, NULL, 5),
  (6, '60 ml. de Licor de Cassis', 60, 'ml', 1),
  (6, '30 ml. de Jugo de pomelo rosado', 30, 'ml', 2),
  (6, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (6, '10/12 hojas de menta', 10, 'hoja', 4),
  (6, 'Completar con soda', NULL, NULL, 5),
  (7, '30 ml. de vodka', 30, 'ml', 1),
  (7, '30 ml. de Lemoncello', 30, 'ml', 2),
  (7, '30 ml. de Jugo de limón', 30, 'ml', 3),
  (7, '30 ml. de Almíbar simple', 30, 'ml', 4),
  (7, '10/12 hojas de menta', 10, 'hoja', 5),
  (7, 'Completar con soda', NULL, NULL, 6),
  (8, '60 ml. de Hierro Quina', 60, 'ml', 1),
  (8, '30 ml. de Jugo de pomelo rosado', 30, 'ml', 2),
  (8, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (8, '10/12 hojas de menta', 10, 'hoja', 4),
  (8, 'Completar con tónica', NULL, NULL, 5),
  (9, '60 ml. de Bourbon', 60, 'ml', 1),
  (9, '15 ml. de Almíbar simple', 15, 'ml', 2),
  (9, '10/12 hojas de menta', 10, 'hoja', 3),
  (9, 'Completar con un golpe de soda', NULL, NULL, 4),
  (10, '60 ml. de Pimm''s', 60, 'ml', 1),
  (10, '30 ml. de Jugo de pomelo rosado', 30, 'ml', 2),
  (10, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (10, '10/12 hojas de menta', 10, 'hoja', 4),
  (10, 'Completar con soda', NULL, NULL, 5),
  (11, '60 ml. de Licor de Parfait Amour', 60, 'ml', 1),
  (11, '30 ml. de Jugo de pomelo/limón', 30, 'ml', 2),
  (11, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (11, '10/12 hojas de menta', 10, 'hoja', 4),
  (11, 'Completar con soda', NULL, NULL, 5),
  (12, '30 ml. de Ron', 30, 'ml', 1),
  (12, '30 ml. de Malibú', 30, 'ml', 2),
  (12, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (12, '30 ml. de jugo de limón', 30, 'ml', 4),
  (12, '10/12 hojas de menta', 10, 'hoja', 5),
  (12, 'Completar con soda', NULL, NULL, 6),
  (13, '45 ml. de Scotch Whisky', 45, 'ml', 1),
  (13, '45 ml. de Vermú Rojo', 45, 'ml', 2),
  (13, '3 dashes de Bitter Angostura', 3, 'dash', 3),
  (14, '60 ml. de Gin London Dry', 60, 'ml', 1),
  (14, '30 ml. de Vermú Seco', 30, 'ml', 2),
  (15, '45 ml. de Gin', 45, 'ml', 1),
  (15, '45 ml. de Vermú seco', 45, 'ml', 2),
  (15, '15 ml. de Triple Sec', 15, 'ml', 3),
  (15, '15 ml. de Apricot Brandy', 15, 'ml', 4),
  (16, '45 ml. de Gin London Dry', 45, 'ml', 1),
  (16, '45 ml. de Vermú Rojo', 45, 'ml', 2),
  (16, '1 dash de Fernet Branca', 1, 'dash', 3),
  (17, '45 ml. de Campari', 45, 'ml', 1),
  (17, '45 ml. de Vermouth Rosso', 45, 'ml', 2),
  (18, '30 ml. de Gin London Dry', 30, 'ml', 1),
  (18, '30 ml. de Campari', 30, 'ml', 2),
  (18, '30 ml. de Vermouth Rosso', 30, 'ml', 3),
  (19, '60 ml. de Vodka', 60, 'ml', 1),
  (19, '30 ml. de Licor de café', 30, 'ml', 2),
  (20, '40% Aperol', 40, NULL, 1),
  (20, '40% espumante', 40, NULL, 2),
  (20, '20% soda', 20, NULL, 3),
  (21, '30 ml. de Campari', 30, 'ml', 1),
  (21, '30 ml. de Vermú Rojo', 30, 'ml', 2),
  (21, 'Completar con soda', NULL, NULL, 3),
  (22, '30 ml. de Campari', 30, 'ml', 1),
  (22, '30 ml. de Vermouth Rosso', 30, 'ml', 2),
  (22, '30 ml. de Champaña', 30, 'ml', 3),
  (23, '45 ml. de Campari', 45, 'ml', 1),
  (23, '45 ml. de Vermú Seco', 45, 'ml', 2),
  (24, '45 ml. de Fernet Branca', 45, 'ml', 1),
  (24, '45 ml. de Vermú Rosso', 45, 'ml', 2),
  (24, 'Completar con soda', NULL, NULL, 3),
  (25, '60 ml. de Whiskey Bourbon', 60, 'ml', 1),
  (25, '15/30 ml. de Almíbar simple', 15, 'ml', 2),
  (25, '3 dashes de Bitter Angostura', 3, 'dash', 3),
  (26, '45 ml. de Gin London Dry', 45, 'ml', 1),
  (26, '15 ml. de Licor Marrasquino', 15, 'ml', 2),
  (26, '15 ml. de Jugo de Limón', 15, 'ml', 3),
  (26, '1 bsp de Crema de Violetas', 1, 'bsp', 4),
  (27, '60 ml. de Pisco', 60, 'ml', 1),
  (27, '15 ml. de Almíbar Simple', 15, 'ml', 2),
  (27, '15 ml. de Jugo de Limón', 15, 'ml', 3),
  (27, '1 clara de huevo', 1, NULL, 4),
  (28, '60 ml. de Ron', 60, 'ml', 1),
  (28, '15 ml. de Almíbar Simple', 15, 'ml', 2),
  (28, '15 ml. de Jugo de Limón', 15, 'ml', 3),
  (29, '60 ml. de Ron', 60, 'ml', 1),
  (29, '15 ml. de Licor Marrasquino', 15, 'ml', 2),
  (29, '30 ml. de Jugo de Pomelo Rosado', 30, 'ml', 3),
  (29, '15 ml. de Jugo de Limón', 15, 'ml', 4),
  (30, '22.5 ml. de Gin', 22.5, 'ml', 1),
  (30, '22.5 ml. de Chartreuse Green', 22.5, 'ml', 2),
  (30, '22.5 ml. de Marraschino', 22.5, 'ml', 3),
  (30, '22.5 ml. de Jugo de Limón', 22.5, 'ml', 4),
  (31, '22.5 ml. de Brandy', 22.5, 'ml', 1),
  (31, '22.5 ml. de Grand Marnier', 22.5, 'ml', 2),
  (31, '22.5 ml. de Apricot Brandy', 22.5, 'ml', 3),
  (31, '22.5 ml. de Jugo de Naranja', 22.5, 'ml', 4),
  (31, '1 clara de huevo', 1, NULL, 5),
  (32, '45 ml. de Gin', 45, 'ml', 1),
  (32, '15 ml. de Jugo de Limón', 15, 'ml', 2),
  (32, '15 ml. de Almíbar simple', 15, 'ml', 3),
  (32, 'Completar con soda', NULL, NULL, 4),
  (33, '45 ml. de Gin', 45, 'ml', 1),
  (33, '15 ml. de Jugo de Limón', 15, 'ml', 2),
  (33, '15 ml. de Almíbar simple', 15, 'ml', 3),
  (33, 'Completar con espumante', NULL, NULL, 4),
  (34, '45 ml. de vodka', 45, 'ml', 1),
  (34, '30 ml. de jugo de mix de cítricos', 30, 'ml', 2),
  (34, '15 ml. de Almíbar simple', 15, 'ml', 3),
  (35, '60 ml. de Gin', 60, 'ml', 1),
  (35, '30 ml. de almíbar de miel', 30, 'ml', 2),
  (35, '30 ml. de jugo de limón', 30, 'ml', 3),
  (36, '60 ml. de Scotch Whisky', 60, 'ml', 1),
  (36, '15 ml. de Almíbar de miel', 15, 'ml', 2),
  (36, '15 ml. de jugo de limón', 15, 'ml', 3),
  (36, '3 rodajas de jengibre machacadas y topping de Single Malt', 3, 'rodaja', 4),
  (37, '22.5 ml. de Mezcal', 22.5, 'ml', 1),
  (37, '22.5 ml. de Aperol', 22.5, 'ml', 2),
  (37, '15 ml. de Strega', 15, 'ml', 3),
  (37, '7.5 ml. de Chartreuse verde', 7.5, 'ml', 4),
  (37, '22.5 ml. de jugo de limón', 22.5, 'ml', 5),
  (38, '15 ml. de London Dry Gin', 15, 'ml', 1),
  (38, '30 ml. de Amargo Obrero', 30, 'ml', 2),
  (38, '22.5 ml. de Licor de sauco', 22.5, 'ml', 3),
  (38, '30 ml. de jugo de mandarina', 30, 'ml', 4),
  (39, '60 ml. de gin', 60, 'ml', 1),
  (39, '30 ml. de almíbar', 30, 'ml', 2),
  (39, '30 ml. de jugo de limón', 30, 'ml', 3),
  (39, '6/8 hojas de albahaca', 6, 'hoja', 4),
  (40, '30 ml. de Gin', 30, 'ml', 1),
  (40, '30 ml. de Strega', 30, 'ml', 2),
  (40, '15 ml. de Apricot Brandy', 15, 'ml', 3),
  (40, '15 ml. de Smirnoff Raspberry', 15, 'ml', 4),
  (40, '30 ml. de jugo de limón', 30, 'ml', 5),
  (40, '2 dashes de Orange Bitter Angostura', 2, 'dash', 6),
  (41, '60 ml. de ron', 60, 'ml', 1),
  (41, '30 ml. de almíbar', 30, 'ml', 2),
  (41, '30 ml. de jugo de limón', 30, 'ml', 3),
  (41, '6/8 hojas de menta', 6, 'hoja', 4),
  (42, '30 ml. de tequila', 30, 'ml', 1),
  (42, '15 ml. de mezcal', 15, 'ml', 2),
  (42, '22.5 ml. de Cherry Brandy', 22.5, 'ml', 3),
  (42, '22.5 ml. de Vermú Rosso', 22.5, 'ml', 4),
  (42, '22.5 ml. de jugo de naranja', 22.5, 'ml', 5),
  (43, '15 ml. de vodka', 15, 'ml', 1),
  (43, '30 ml. de Cherry Brandy', 30, 'ml', 2),
  (43, '30 ml. de jugo de pomelo rosado', 30, 'ml', 3),
  (43, '15 ml. de almíbar simple', 15, 'ml', 4),
  (43, '1 clara de huevo', 1, NULL, 5),
  (44, '60 ml. de Amargo Obrero', 60, 'ml', 1),
  (44, '30 ml. de jugo de pomelo rosado', 30, 'ml', 2),
  (44, '30 ml. de Almíbar simple', 30, 'ml', 3),
  (44, 'Completar con soda', NULL, NULL, 4),
  (45, '45 ml. de Tequila', 45, 'ml', 1),
  (45, '22.5 ml. de Triple Sec', 22.5, 'ml', 2),
  (45, '22.5 ml. de jugo de limón', 22.5, 'ml', 3),
  (45, '5 ml. de Almíbar Simple', 5, 'ml', 4),
  (46, '60 ml. de Cachaça', 60, 'ml', 1),
  (46, '1 lima cortada en 6 partes', 1, NULL, 2),
  (46, '1 cucharada sopera de azúcar', 1, 'cda', 3),
  (47, '60 ml. de Ron Blanco', 60, 'ml', 1),
  (47, '6 frutillas sin cabo', 6, NULL, 2),
  (47, '1.5 cda. sopera de azúcar', 1.5, 'cda', 3),
  (48, '45 ml. de Baileys', 45, 'ml', 1),
  (48, '15 ml. de Ron Blanco', 15, 'ml', 2),
  (48, '6 frutillas sin cabo', 6, NULL, 3),
  (48, '1.5 cda. sopera de azúcar', 1.5, 'cda', 4),
  (49, '60 ml. de espumante', 60, 'ml', 1),
  (49, '15 ml. de Almíbar Simple', 15, 'ml', 2),
  (49, '15 ml. de jugo de limón', 15, 'ml', 3),
  (50, '30 ml. de un destilado (Ron Añejo / Whisky / Vodka)', 30, 'ml', 1),
  (50, '30 ml. de un licor cremoso (Amarula / Sheridan''s / Baileys)', 30, 'ml', 2),
  (50, '30 ml. de leche', 30, 'ml', 3),
  (50, '15 ml. de Almíbar simple', 15, 'ml', 4),
  (50, '1 cda. sopera de café', 1, 'cda', 5),
  (51, '30 ml. de jugo de limón', 30, 'ml', 1),
  (51, '60 ml. de almíbar simple', 60, 'ml', 2),
  (51, '150 ml. de agua/soda', 150, 'ml', 3),
  (51, 'Opcional: 4/5 láminas de jengibre', NULL, NULL, 4),
  (51, '6/8 hojas de menta fresca', 6, 'hoja', 5),
  (52, '90 ml. de jugo de limón', 90, 'ml', 1),
  (52, '180 ml. de almíbar simple', 180, 'ml', 2),
  (52, '450 ml. de agua/soda', 450, 'ml', 3),
  (52, 'Opcional: 12 láminas de jengibre', NULL, NULL, 4),
  (52, '20 hojas de menta fresca', 20, 'hoja', 5);

-- ---------- recipe_tags ----------
INSERT INTO recipe_tags (recipe_id, tag_id) VALUES
  (1, 32),
  (1, 26),
  (1, 13),
  (2, 9),
  (2, 26),
  (2, 13),
  (3, 15),
  (3, 26),
  (3, 31),
  (4, 29),
  (4, 26),
  (4, 31),
  (5, 20),
  (5, 26),
  (6, 10),
  (6, 26),
  (6, 31),
  (7, 38),
  (7, 36),
  (7, 26),
  (7, 13),
  (8, 21),
  (8, 26),
  (8, 31),
  (9, 39),
  (9, 26),
  (10, 28),
  (10, 26),
  (10, 31),
  (11, 26),
  (11, 31),
  (12, 32),
  (12, 25),
  (12, 26),
  (12, 13),
  (13, 37),
  (13, 39),
  (13, 3),
  (14, 19),
  (14, 37),
  (15, 19),
  (15, 37),
  (15, 6),
  (15, 5),
  (15, 36),
  (16, 19),
  (16, 17),
  (16, 37),
  (17, 9),
  (17, 37),
  (18, 19),
  (18, 9),
  (18, 37),
  (19, 38),
  (19, 23),
  (19, 8),
  (20, 4),
  (20, 16),
  (21, 9),
  (21, 37),
  (22, 9),
  (22, 37),
  (22, 16),
  (23, 9),
  (23, 37),
  (24, 17),
  (24, 37),
  (25, 39),
  (25, 3),
  (26, 19),
  (26, 12),
  (26, 24),
  (26, 13),
  (27, 30),
  (27, 14),
  (27, 13),
  (28, 32),
  (28, 13),
  (29, 32),
  (29, 12),
  (29, 31),
  (29, 13),
  (30, 19),
  (30, 12),
  (30, 11),
  (30, 13),
  (31, 6),
  (31, 5),
  (31, 36),
  (31, 14),
  (32, 19),
  (32, 13),
  (33, 19),
  (33, 16),
  (33, 13),
  (34, 38),
  (34, 13),
  (35, 19),
  (35, 13),
  (36, 39),
  (36, 22),
  (36, 13),
  (37, 4),
  (37, 27),
  (37, 11),
  (37, 34),
  (37, 13),
  (38, 19),
  (38, 2),
  (39, 19),
  (39, 1),
  (39, 13),
  (40, 19),
  (40, 6),
  (40, 5),
  (40, 34),
  (40, 3),
  (40, 13),
  (41, 32),
  (41, 26),
  (41, 13),
  (42, 37),
  (42, 35),
  (42, 27),
  (42, 6),
  (42, 12),
  (43, 38),
  (43, 6),
  (43, 12),
  (43, 31),
  (43, 14),
  (44, 2),
  (44, 31),
  (45, 35),
  (45, 36),
  (45, 13),
  (46, 7),
  (47, 32),
  (47, 18),
  (48, 32),
  (48, 24),
  (48, 18),
  (49, 16),
  (49, 13),
  (50, 32),
  (50, 38),
  (50, 39),
  (50, 24),
  (50, 8),
  (51, 26),
  (51, 22),
  (51, 13),
  (51, 33),
  (52, 26),
  (52, 22),
  (52, 13),
  (52, 33);

COMMIT;

-- Topics: se dejan SIN cargar en esta etapa (decision del plan v2).
-- Propuesta para habilitar mas adelante:
--   INSERT INTO topics (name, slug) VALUES
--     ('Clasicos','clasicos'),
--     ('Refrescantes / Verano','refrescantes-verano'),
--     ('Batidos con huevo','batidos-con-huevo'),
--     ('Frozen','frozen'),
--     ('Machacados','machacados'),
--     ('Con espuma / Champagne','con-espuma-champagne'),
--     ('Amargos / Aperitivos','amargos-aperitivos');
